version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    restart: always
    networks:
      - react-express
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3001
      - VITE_FRONTEND_URL=https://fruitscash.onrender.com
      - VITE_AFFILIATE_SUPPORT_CONTACT_LINK=https://wa.me/5521970707070?text=Preciso%20de%20ajuda%20no%20FruitsCash!
      - VITE_SUPPORT_EMAIL=sac.fruitscash@gmail.com

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - react-express
    environment:
      - MONGO_URL=mongodb+srv://mybet:zjfzLuCDodlFALoj@cluster0.1llcjkp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DATABASE=fruitscash
      - PORT=3001
      - JWT_SECRET=beibebeibedobeibedobiruleibeleibe
      - CLIENT_URL=https://fruitscash.onrender.com
      - SERVER_URL=https://fruitscash.onrender.com
      - GMAIL_USER=sac.fruitscash@gmail.com
      - GMAIL_APP_PASSWORD="ifny mpel kvvw irrm"
      - CPA_PERCENTAGE=0.1
      - REVSHARE_PERCENTAGE=0.1
      - SUITPAY_URL=https://sandbox.ws.suitpay.app
      - SUITPAY_CLIENT_ID=testesandbox_1687443996536
      - SUITPAY_CLIENT_SECRET=5b7d6ed3407bc8c7efd45ac9d4c277004145afb96752e1252c2082d3211fe901177e09493c0d4f57b650d2b2fc1b062d

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - react-express
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template

networks:
  react-express: