services:
  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    restart: unless-stopped
    networks:
      - react-express
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    env_file: ./client/.env

  server:
    container_name: express-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - react-express
    ports:
      - "3001:3001"
    env_file: ./server/.env

networks:
  react-express: